import Head from "next/head";
import { signIn, useSession, signOut } from "next-auth/react";

export default function Home() {
  const { data, status } = useSession();
  console.log(data);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <p>status: {status}</p>
        <p>{data?.user?.name}</p>
        {data?.user ? (
          <button type="button" onClick={() => signOut()}>
            Google Logout
          </button>
        ) : (
          // <button type="button" onClick={() => signIn()}>
          <button type="button" onClick={() => signIn("google")}>
            Google Login
          </button>
        )}
      </main>
    </>
  );
}
